when:
  branch: main
  event: [push, manual]

steps:
  codebergpkgs:
    image: gradle:8.12-jdk17-alpine@sha256:a013d2269e0e2464ee097af6c8f3ac70c9dfaa49cadd3a2fade50aa65407b045
    commands:
      - ./gradlew publishPluginPublicationToCodebergPackagesRepository
    secrets:
      - source: CODEBERG_TOKEN
        target: CODEBERG_TOKEN
 
